# ASP.NET

# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
 branches:
    include:
    - master
 paths:
    include:
    - src/Clients/WebApp/*
    - src/Domain/*
    - src/Application/*
    - src/Infrastructure/* 

pool:
  image: 'ubuntu-latest'
# pool:
#     name: Default

variables:
- name: buildConfiguration 
  value: 'Release'
- name: solution 
  value: '**/SmartHome.Clients.WebApp.csproj'
- name: rootSolution 
  value: '**/SmartHome.App.sln'
- name: buildPlatform
  value: 'Any CPU'
- name: webAppBuild
  value: '$(Pipeline.Workspace)/SmartHome.WebApp-build/Clients/WebApp'
- group: Pipelines Variables


stages:
- stage: Build
  displayName: 'Build'
  jobs:
  - job:  BuildWebApp
    displayName: 'Build Web Application'
    steps:
      - task: mirror-git-repository-vsts-task@1
        displayName: 'Create repository mirror on GitHub'
        continueOnError: true
        inputs:
          sourceGitRepositoryUri: 'https://dev.azure.com/kamilmrzyglod/Smart%20home/_git/SmartHome.App'
          sourceGitRepositoryPersonalAccessToken: $(DevOpsReposAccessToken)
          destinationGitRepositoryUri: 'https://github.com/kmrzyglod/SmartHome.App.git'
          destinationGitRepositoryPersonalAccessToken: $(GitHubAccessToken)
      - task: DotNetCoreCLI@2
        displayName: 'Build Blazor web app project'
        inputs:
          command: 'build'
          arguments: '--configuration $(buildConfiguration)'
          projects: '$(solution)'   
      - task: PublishPipelineArtifact@1
        displayName:  Publish artifacts
        inputs:
          targetPath: 'src' 
          artifactName: 'SmartHome.WebApp-build'
- stage: PublishTestVersion
  displayName: 'Publish Test version artifacts'
  jobs:
  - job:  "PublishTestVersion"
    displayName:  Publish Test version artifacts
    steps:
    - checkout: none
    - download: current
      displayName:  Download artifacts
      artifact: 'SmartHome.WebApp-build'
    - task: Bash@3
      displayName: 'Copy proper appsettings.json'
      inputs:
        targetType: inline
        script: 'cp "$(webAppBuild)/bin/Release/net6.0/wwwroot/appsettings/appsettings-prod.json"  "$(webAppBuild)/bin/Release/net6.0/wwwroot/appsettings.json"'
    # - task: DotNetCoreCLI@2
    #   displayName:  Restore packages
    #   inputs:
    #     command: 'restore'
    #     projects: '$(Pipeline.Workspace)/SmartHome.WebApp-build/SmartHome.Clients.WebApp.csproj'
    - task: DotNetCoreCLI@2
      displayName:  Publish Blazor client project
      inputs:
        command: 'publish'
        arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory) --no-build --no-restore'
        zipAfterPublish: false
        projects: '$(webAppBuild)/SmartHome.Clients.WebApp.csproj'
        publishWebProjects: false
    - task: PublishPipelineArtifact@1
      displayName:  Publish artifacts
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)' 
        artifactName: 'SmartHome.WebApp-test'
      